"""
PRAJA Civic Issue Detector — Python AI Service
Uses CLIP (openai/clip-vit-base-patch32) for zero-shot image classification.
No API keys required. Runs fully offline after first model download (~600 MB).

Target acceptance classes (strict):
- Garbage / trash dump
- Dirty public toilet
- Dirty road / unsanitary street
- Pothole / damaged road surface
- Stray dogs causing public nuisance or risk

All other images (car, bus, selfie, nature, random objects, etc.) are rejected.

Start: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
"""

from fastapi import FastAPI, File, UploadFile
from fastapi.middleware.cors import CORSMiddleware
from PIL import Image
import io
import torch
from transformers import CLIPProcessor, CLIPModel
import threading

app = FastAPI(title="PRAJA Civic Issue Detector")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

# ── Model state ───────────────────────────────────────────────────────────────
_model = None
_processor = None
_model_ready = False
_model_error = None


def _load_model():
    global _model, _processor, _model_ready, _model_error
    try:
        print("Loading CLIP model (first run downloads ~600 MB, cached after that)...")
        _model = CLIPModel.from_pretrained("openai/clip-vit-base-patch32")
        _processor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")
        _model.eval()
        _model_ready = True
        print("✅ Model ready — listening on http://localhost:8000")
    except Exception as e:
        _model_error = str(e)
        print(f"❌ Model failed to load: {e}")


# Load in background so the API starts immediately and stays responsive
threading.Thread(target=_load_model, daemon=True).start()

# ── Text prompts ──────────────────────────────────────────────────────────────

TARGET_CLASS_PROMPTS = [
    ("Waste Management", "a real photo of garbage piled on street, trash dump, littered public place, waste management issue"),
    ("Sanitation", "a real photo of dirty public toilet, unclean toilet area, unhygienic restroom in public place"),
    ("Sanitation", "a real photo of dirty road with filth, sewage, unhygienic waste on street"),
    ("Road & Infrastructure", "a real photo of pothole on road, damaged asphalt, broken road surface"),
    ("Public Safety", "a real photo of stray dogs on street causing public nuisance or safety concern"),
]

NON_TARGET_PROMPTS = [
    "a clear photo of a car or parked car",
    "a clear photo of a bus or truck",
    "a selfie or portrait of a person",
    "an indoor room, office, classroom, or home scene",
    "a landscape, sky, trees, or nature photo",
    "a random object or product photo not related to civic issue",
    "a clean road with no visible issue",
]

REAL_PHOTO_PROMPTS = [
    "a real smartphone photo taken in the real world",
    "an authentic camera photo of a real street scene",
    "an unedited real-life photo with natural lighting",
]

AI_GENERATED_PROMPTS = [
    "an ai-generated image",
    "a synthetic rendered image",
    "digital artwork generated by ai",
    "an image with ai generated watermark or generated text overlay",
    "a fake image generated by text-to-image model",
    "an artificial image with unnatural details",
]

AI_WATERMARK_PROMPTS = [
    "image contains ai generated watermark",
    "image has synthetic watermark or ai model branding",
    "image has generated badge or fake camera overlay",
]

SEVERITY = {
    "Road & Infrastructure": "High",
    "Waste Management":      "Medium",
    "Public Safety":         "Critical",
    "Sanitation":            "High",
}

DEPARTMENT = {
    "Road & Infrastructure": "Public Works Department (PWD)",
    "Waste Management":      "Municipal Sanitation / Solid Waste Management",
    "Public Safety":         "Municipal Engineering Department",
    "Sanitation":            "Drainage Department / Underground Drainage",
}

# Lowered thresholds to accept real civic complaint photos (potholes, garbage, etc)
# while still rejecting non-civic images
STRICT_CLASS_THRESHOLD = 0.28  # Reduced from 0.33 to accept more valid civic issues
TARGET_VS_NON_TARGET_GAP = 0.05  # Reduced from 0.08 for better real-world detection
AI_GENERATED_THRESHOLD = 0.42
AI_VS_REAL_GAP = 0.08
AI_LIKELIHOOD_THRESHOLD = 0.50
WATERMARK_THRESHOLD = 0.32

# ── Helper ────────────────────────────────────────────────────────────────────

def clip_probs(image: Image.Image, texts: list[str]) -> list[float]:
    inputs = _processor(
        text=texts, images=image,
        return_tensors="pt", padding=True, truncation=True
    )
    with torch.no_grad():
        out = _model(**inputs)
    return out.logits_per_image[0].softmax(dim=0).tolist()

# ── Routes ────────────────────────────────────────────────────────────────────

@app.get("/")
def root():
    return {
        "service": "PRAJA Civic Issue Detector",
        "status": "ready" if _model_ready else "initializing",
        "endpoints": {
            "health": "GET /health",
            "analyze": "POST /analyze  (send image as multipart form-data with field 'file')"
        }
    }


@app.get("/health")
def health():
    if _model_error:
        return {"status": "error", "detail": _model_error}
    if not _model_ready:
        return {"status": "initializing", "detail": "CLIP model is still loading, please retry in a moment"}
    return {"status": "ok"}


@app.post("/analyze")
async def analyze(file: UploadFile = File(...)):
    # ── Guard: model not ready yet ────────────────────────────────────────────
    if _model_error:
        return {
            "isCivicIssue": False,
            "status": "error",
            "error": f"AI model failed to load: {_model_error}. Check network access to huggingface.co and restart the service.",
        }

    if not _model_ready:
        return {
            "isCivicIssue": False,
            "status": "initializing",
            "error": "AI model is still loading (downloading ~600 MB on first run). Please wait 30–60 seconds and try again.",
        }

    # Read & decode image
    raw = await file.read()
    try:
        image = Image.open(io.BytesIO(raw)).convert("RGB")
    except Exception as e:
        return {"isCivicIssue": False, "error": f"Cannot read image: {e}"}

    # ── Stage 0: authenticity check (real photo vs AI-generated) ────────────
    real_probs = clip_probs(image, REAL_PHOTO_PROMPTS)
    ai_probs = clip_probs(image, AI_GENERATED_PROMPTS)
    watermark_probs = clip_probs(image, AI_WATERMARK_PROMPTS)

    best_real_prob = max(real_probs)
    best_ai_prob = max(ai_probs)
    best_watermark_prob = max(watermark_probs)

    ai_likelihood = best_ai_prob / (best_ai_prob + best_real_prob + 1e-6)

    is_likely_ai_generated = (
        (
            best_ai_prob >= AI_GENERATED_THRESHOLD
            and (best_ai_prob - best_real_prob) >= AI_VS_REAL_GAP
        )
        or ai_likelihood >= AI_LIKELIHOOD_THRESHOLD
        or best_watermark_prob >= WATERMARK_THRESHOLD
    )

    authenticity = {
        "isLikelyAIGenerated": is_likely_ai_generated,
        "realPhotoConfidence": int(best_real_prob * 100),
        "aiGeneratedConfidence": int(best_ai_prob * 100),
        "aiLikelihood": round(ai_likelihood, 3),
        "watermarkConfidence": int(best_watermark_prob * 100),
    }

    if is_likely_ai_generated:
        return {
            "isCivicIssue": False,
            "imageQuality": "good",
            "mainSubject": "Likely synthetic image",
            "reason": (
                "This image appears to be AI-generated or synthetic. "
                "Please upload a real camera photo of the actual issue location."
            ),
            "authenticity": authenticity,
        }

    # ── Stage 1: civic vs non-civic ───────────────────────────────────────────
    target_texts = [p[1] for p in TARGET_CLASS_PROMPTS]
    target_probs = clip_probs(image, target_texts)
    best_target_idx = target_probs.index(max(target_probs))
    best_target_prob = target_probs[best_target_idx]
    best_target_label = TARGET_CLASS_PROMPTS[best_target_idx][0]

    non_target_probs = clip_probs(image, NON_TARGET_PROMPTS)
    best_non_target_prob = max(non_target_probs)

    confidence = int(best_target_prob * 100)
    is_civic = (
        best_target_prob >= STRICT_CLASS_THRESHOLD
        and (best_target_prob - best_non_target_prob) >= TARGET_VS_NON_TARGET_GAP
    )

    if not is_civic:
        return {
            "isCivicIssue": False,
            "imageQuality": "good",
            "mainSubject":  "Non-civic image",
            "reason": (
                "Image is not relevant for this complaint type. "
                "Please upload only: garbage, dirty toilet, dirty road, pothole, or stray dogs."
            ),
            "authenticity": authenticity,
            "confidence": confidence,
            "acceptedClasses": [
                "garbage",
                "dirty toilet",
                "dirty road",
                "pothole",
                "stray dogs",
            ],
        }

    # ── Stage 2: strict category mapping (already selected in Stage 1) ──────
    category   = best_target_label
    severity   = SEVERITY[category]
    dept       = DEPARTMENT[category]
    urgency    = 1 if severity == "Critical" else (3 if severity == "High" else 7)

    return {
        "isCivicIssue":  True,
        "imageQuality":  "good",
        "authenticity": authenticity,
        "category":      category,
        "severity":      severity,
        "confidence":    confidence,
        "title":         f"{category} issue detected",
        "description": (
            f"AI detected a {severity.lower()}-priority {category.lower()} issue. "
            "Please add specific details in the description to help authorities act faster."
        ),
        "tags": [
            category.lower().replace(" & ", "-").replace(" ", "-"),
            severity.lower(),
            "civic-issue",
            "india",
        ],
        "visualEvidence": [
            f"Classified as: {category}",
            f"Severity level: {severity}",
            f"Model confidence: {confidence}%",
        ],
        "estimatedImpact": {
            "peopleAffected": "50–200 residents",
            "urgencyDays":    urgency,
            "safetyRisk":     severity in ("Critical", "High"),
            "trafficImpact":  category == "Road & Infrastructure",
        },
        "aiRecommendations": {
            "department":          dept,
            "immediateAction":     f"Dispatch a field team to inspect the {category.lower()} issue",
            "permanentFix":        f"Restore and repair the {category.lower()} infrastructure",
            "estimatedRepairTime": "1–2 days" if severity == "Critical" else "3–7 days",
            "estimatedCostINR":    "10,000–50,000",
            "requiredResources":   ["Field inspection team", "Repair materials", "Equipment"],
            "suggestedATR": (
                f"The reported {category} issue has been verified and forwarded to {dept} "
                "for immediate action. Resolution expected within the stipulated timeframe."
            ),
        },
        "locationClues": {
            "locationType":     "unknown",
            "timeOfDay":        "unclear",
            "weatherCondition": "unclear",
            "nearbyLandmarks":  [],
            "urbanRural":       "unclear",
            "roadType":         "unknown",
        },
        "relatedIssues": [],
    }
